package common

const (
	SUCCESS_CODE = 200
	SUCCESS_MESS = "SUCCESS MESSAGE"

	UNKNOW_ERR_CODE = 1
	UNKNOW_ERR_MESS = "Unknow error"

	DB_ERR_CODE = 2
	DB_ERR_MESS = "Database error"
)

const (
	USER_NOT_EXIT_CODE = 10000
	USER_NOT_EXIT_MESS = "User not exit"

	WRONG_PASSWORD_ERROR_CODE = 10001
	WRONG_PASSWORD_ERROR_MESS = "Wrong password!"

	USER_EXITED_ERR_CODE = 10002
	USER_EXITED_ERR_MESS = "User exited"
)
