// Code generated by goctl. DO NOT EDIT.
package types

type Result struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type User struct {
	ID       int64  `json:"id"`
	Name     string `json:"name"`
	FullName string `json:"fullName"`
	Email    string `json:"email"`
	Role     int64  `json:"role"`
}

type LoginReq struct {
	Username string `form:"username"` //	username
	Password string `form:"password"` // 	password
}

type LoginRes struct {
	Token  string `json:"token"`
	User   User   `json:"user"`
	Result Result `json:"result"`
}

type RegisterReq struct {
	Fullname string `form:"fullname"`
	Username string `form:"username"`
	Password string `form:"password"`
	Email    string `form:"email"`
}

type RegisterRes struct {
	Token  string `json:"token"`
	User   User   `json:"user"`
	Result Result `json:"result"`
}

type GetUserReq struct {
	UserID int64 `path:"user_id"`
}

type GetUserRes struct {
	Result Result `json:"result"`
	User   User   `json:"user"`
}
